package share

const (
	ROOM_USER_MAX = 1000
)

const (
	PACKET_TYPE_LOGIN       = 1
	PACKET_TYPE_LOGOUT      = 3
	PACKET_TYPE_CREATE_ROOM = 5
	PACKET_TYPE_JOIN_ROOM   = 7
	PACKET_TYPE_LEAVE_ROOM  = 9
	PACKET_TYPE_SINGLE_CHAT = 11
	PACKET_TYPE_MULTI_CHAT  = 13
	PACKET_TYPE_KICK = 15

	PACKET_TYPE_SERVER_REGISTER      = 1001
	PACKET_TYPE_SERVER_REGISTER_BACK = 1002
	PACKET_TYPE_CLIENT_REGISTER      = 1003
	PACKET_TYPE_SERVER_SYNC_INFO     = 1005
)
